version: '2'

services:
  redis:
    image: 'redis:4.0-alpine'
    volumes:
      - 'redis:/data'
  shortener:
    depends_on:
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
